jobs:
  file-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for staged file deletions
        run: |
          if git diff --cached --name-status | grep '^D'; then
            echo "Error: File deletion detected. List of deleted files:";
            git diff --cached --name-status | grep '^D' | awk '{print $2}';
            exit 1;
          fi
