name: Dev Approval Workflow

on:
  workflow_run:
    workflows: ["Dev Deployment Workflow"]
    types:
      - completed

jobs:
  approval:
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:
      - name: Check Approval Status
        run: echo "Check if approval is required"

      - name: Perform Removal
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.workflow.name == 'Dev Deployment Workflow' }}
        run: echo "Removing resource from dev environment"

