name: Deploy Load Balancer

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Create or Remove the Load Balancer'
        required: true
        default: 'create'
        options:
          - create
          - remove
      resource-group:
        description: 'Azure Resource Group'
        required: true
      location:
        description: 'Azure Region'
        required: true
      lb-name:
        description: 'Load Balancer Name'
        required: true
      frontend-ip:
        description: 'Frontend IP Configuration Name'
        required: true
      environment:
        description: 'Environment (dev, prod, UAT)'
        required: true
        type: choice
        options:
          - dev
          - prod
          - UAT

jobs:
  deploy-lb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Environment
        run: echo "Deploying to ${{ inputs.environment }} environment"

      - name: Deploy Load Balancer
        if: inputs.action == 'create'
        run: |
          az network lb create --resource-group ${{ inputs.resource-group }} \
            --name ${{ inputs.lb-name }} --location "${{ inputs.location }}" \
            --frontend-ip-name ${{ inputs.frontend-ip }}
      - name: Remove Load Balancer
        if: inputs.action == 'remove'
        run: |
          az network lb delete --resource-group ${{ inputs.resource-group }} \
            --name ${{ inputs.lb-name }}
